spring:
  profiles:
    default: local

---

spring:
  profiles:
    active: local

---

spring:
  profiles:
    active: dev

---

#common
spring:
  application:
    name: eureka

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  servlet:
    encoding:
      charset: UTF-8
  port: 8761

logging:
  config: classpath:log4j2.xml

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        exclude: heapdump, threaddump, restart
        include: health, refresh
  server:
    port: 8769
